name: menomoodhack
description: Control menopause mood swings. Based on meditation and music techniques.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  curved_navigation_bar: ^0.3.2
  dio: ^3.0.9
  flutter_web_browser: ^0.11.0
  json_serializable: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - asset/images/
  fonts:
    - family: Lobster
      fonts:
        - asset: asset/fonts/Lobster-Regular.ttf
    - family: Righteous
      fonts:
        - asset: asset/fonts/Righteous-Regular.ttf